# Sử dụng base image Nginx chính thức
FROM nginx:stable-alpine

# Copy file cấu hình Nginx tùy chỉnh vào container
# File này sẽ ghi đè lên file cấu hình mặc định
COPY nginx/nginx.conf /etc/nginx/nginx.conf

